[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "msb"
version = "0.1.0"
description = "Mega-Super-Base (MSB) architecture for flexible and extensible Python applications"
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
authors = [
    {name = "Alexey Rudnitskiy", email = "almax1024@gmail.com"}
]
keywords = ["msb", "architecture", "extensible"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: Other/Proprietary License",
]
dependencies = []

[project.urls]
Homepage = "https://github.com/Torward1024/MSB"
Documentation = "https://github.com/Torward1024/MSB/wiki"
Repository = "https://github.com/Torward1024/MSB"
Issues = "https://github.com/Torward1024/MSB/issues"